# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a1e039439a57472eb534b1ffc6f9f75c87f68adbb337174f2e347f973517ff258e99cc7565470442b0d6ec580673665db9eace3ca457441852edce5080c53beb

test:
  secret_key_base: 6e9b21e9dae2c97886cc56057c437a1861309bbe30f3b101c5c9b9f7c9f0da4d08e2b6b67d650ec401c1444ff2e1c80f1ce49ec9f5500b6ad522b8acd9110a57

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
